package:
name: taxcalc
version: 10.1.1

build:
entry_points:
- tc = taxcalc.cli.tc:main

requirements:
build:
- pytest
- setuptools
- python
- mock
- numpy ==1.11.2
- pandas <=0.18.0
- numba
- toolz
- six
run:
- pytest
- setuptools
- python
- mock
- numpy ==1.11.2
- pandas <=0.18.0
- numba
- toolz
- six

test:
commands:
- which tc # [unix]
- where tc # [win]
- tc --help

about:
home: http://www.github.com/OpenSourcePolicyCenter
