# Note jinja template variables added by staged-recipes
# Do not commit statements like: {% set name="some_name" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ source_url }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - pytest
    - setuptools
    - python
    - numpy ==1.10.4
    - pandas >=0.18.0
    - numba
    - toolz
    - six
  run:
    - pytest
    - setuptools
    - python
    - numpy ==1.10.4
    - pandas >=0.18.0
    - numba
    - toolz
    - six

about:
  home: http://www.github.com/OpenSourcePolicyCenter
  summary: Federal Individual Income Tax Microsimulation Model

extra:
  recipe-maintainers:
   - Peter Steinberg
   - TJ Alumbaugh
